### PR TITLE
Generate a static Github page site

### PR DESCRIPTION
**Pull request by kyleconroy**
To generate the site, just run `make site serve`. Iteration speed is still
slow as it has to reparse the trips every time, but this is something we
can easily fix by splitting the trip data JS into a separate build step.

### CODE REVIEW

**Comment by kevinburke** [comment]
Can we add a Travis CI config that running "make stats" does not generate a Git diff?

you can use github.com/kevinburke/differ for this. I use it in the Travis CI config for github.com/kevinburke/go-bindata

**Comment by kevinburke** [comment]
Also can we still wrap the http.FileServer in a handlers.Log? It's nice to see what requests are coming in when you run locally.

**Comment by kyleconroy** [comment]
I sadly can't use `differ` right now, because generating the site requires all the data to be downloaded into the `/data` directory. I can write another PR that loads all the official data before we run tests, which should also catch future breakages.

**Comment by kevinburke** [comment]
Oh, right, that's right.

**Comment by kyleconroy** [comment]
Okay, I think it's ready

**Comment by kevinburke** [comment]
Alright I'm heading to bed so go for it

**Pull request merged**
